import jsPDF from 'jspdf';

interface GroceryItem {
  name: string;
  quantity: number;
  unit: string;
  category: string;
  checked: boolean;
}

const CATEGORY_ORDER = ['produce', 'protein', 'dairy', 'grains', 'pantry', 'frozen', 'condiment'];
const CATEGORY_LABELS: Record<string, string> = {
  produce: 'PRODUCE',
  protein: 'PROTEIN',
  dairy: 'DAIRY',
  grains: 'GRAINS & STARCHES',
  pantry: 'PANTRY',
  frozen: 'FROZEN',
  condiment: 'CONDIMENTS',
};

export function generateGroceryPDF(
  items: GroceryItem[],
  weekStart: string,
  listType: 'weekly' | 'monthly'
) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Title
  const weekDate = new Date(weekStart + 'T00:00:00');
  const dateStr = weekDate.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  const title = `GROCERY LIST — Week of ${dateStr}`;
  const subtitle = listType === 'weekly' ? 'Weekly Fresh Items' : 'Monthly Staples';

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(title, margin, y);
  y += 20;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(subtitle, margin, y);
  y += 8;

  // Divider
  doc.setDrawColor(180);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentWidth, y);
  y += 16;

  // Group by category
  const grouped: Record<string, GroceryItem[]> = {};
  for (const item of items) {
    const cat = item.category || 'pantry';
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(item);
  }

  // Render categories in order
  doc.setTextColor(0);
  for (const cat of CATEGORY_ORDER) {
    const catItems = grouped[cat];
    if (!catItems || catItems.length === 0) continue;

    // Check if we need a new page
    if (y > 700) {
      doc.addPage();
      y = margin;
    }

    // Category header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(CATEGORY_LABELS[cat] || cat.toUpperCase(), margin, y);
    y += 16;

    // Items
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    catItems.sort((a, b) => a.name.localeCompare(b.name));

    for (const item of catItems) {
      if (y > 740) {
        doc.addPage();
        y = margin;
      }

      const qty = item.quantity % 1 === 0 ? String(item.quantity) : item.quantity.toFixed(2).replace(/0+$/, '').replace(/\.$/, '');
      const line = `${qty} ${item.unit}`;

      // Checkbox
      doc.setDrawColor(150);
      doc.setLineWidth(0.5);
      doc.rect(margin, y - 8, 9, 9);

      // Item name
      doc.text(item.name, margin + 16, y);

      // Quantity right-aligned
      doc.setTextColor(100);
      const qtyWidth = doc.getTextWidth(line);
      doc.text(line, margin + contentWidth - qtyWidth, y);
      doc.setTextColor(0);

      y += 16;
    }

    y += 8; // Space between categories
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 30;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Fitness Recomp App', margin, y);
  doc.text(new Date().toLocaleDateString(), margin + contentWidth - doc.getTextWidth(new Date().toLocaleDateString()), y);

  // Download
  const filename = `grocery-${listType}-${weekStart}.pdf`;
  doc.save(filename);
}
