import jsPDF from 'jspdf';

interface MealEntry {
  meal_slot: string;
  recipe_name: string;
  from_batch: boolean;
}

interface DaySummary {
  date: string;
  workout_type: string;
  meals: MealEntry[];
  macro_total: { calories: number; protein: number; carbs: number; fat: number };
}

const WORKOUT_LABELS: Record<string, string> = {
  heavy_upper: 'Heavy Upper',
  heavy_lower: 'Heavy Lower',
  upper_hypertrophy: 'Upper Hypertrophy',
  lower_hypertrophy: 'Lower Hypertrophy',
  abs_forearms: 'Abs + Forearms',
  rest: 'Rest Day',
};

const SLOT_ORDER = ['breakfast', 'lunch', 'dinner', 'snack'];
const SLOT_LABELS: Record<string, string> = {
  breakfast: 'Breakfast',
  lunch: 'Lunch',
  dinner: 'Dinner',
  snack: 'Snack',
};

export function generateMealSchedulePDF(days: DaySummary[], weekStart: string) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Title
  const startDate = new Date(weekStart + 'T00:00:00');
  const endDate = new Date(startDate);
  endDate.setDate(endDate.getDate() + 6);
  const fmt = (d: Date) => d.toLocaleDateString('en-US', { month: 'long', day: 'numeric' });
  const title = `WEEKLY MEAL SCHEDULE`;
  const dateRange = `${fmt(startDate)} – ${fmt(endDate)}, ${startDate.getFullYear()}`;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(title, margin, y);
  y += 18;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(dateRange, margin, y);
  y += 8;

  doc.setDrawColor(180);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentWidth, y);
  y += 20;

  // Track weekly totals
  let totalCal = 0, totalProtein = 0, totalCarbs = 0, totalFat = 0;
  let dayCount = 0;

  doc.setTextColor(0);

  for (const day of days) {
    // Page break check — each day needs ~100pt
    if (y > 640) {
      doc.addPage();
      y = margin;
    }

    const dateObj = new Date(day.date + 'T00:00:00');
    const dayName = dateObj.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).toUpperCase();
    const workoutLabel = WORKOUT_LABELS[day.workout_type] || day.workout_type;

    // Day header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(dayName, margin, y);
    y += 14;

    // Workout
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`Workout: ${workoutLabel}`, margin + 8, y);
    doc.setTextColor(0);
    y += 14;

    // Meals
    doc.setFontSize(10);
    for (const slot of SLOT_ORDER) {
      const meal = day.meals.find(m => m.meal_slot === slot);
      if (!meal) continue;

      const label = SLOT_LABELS[slot] || slot;
      const batchTag = meal.from_batch ? ' (batch)' : '';

      doc.setFont('helvetica', 'bold');
      doc.text(`${label}:`, margin + 8, y);
      const labelWidth = doc.getTextWidth(`${label}: `);

      doc.setFont('helvetica', 'normal');
      doc.text(`${meal.recipe_name}${batchTag}`, margin + 8 + labelWidth, y);
      y += 14;
    }

    // Daily macros
    const m = day.macro_total;
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`${Math.round(m.calories)} cal  |  ${Math.round(m.protein)}g P  |  ${Math.round(m.carbs)}g C  |  ${Math.round(m.fat)}g F`, margin + 8, y);
    doc.setTextColor(0);
    y += 10;

    // Thin divider
    doc.setDrawColor(220);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentWidth, y);
    y += 14;

    totalCal += m.calories;
    totalProtein += m.protein;
    totalCarbs += m.carbs;
    totalFat += m.fat;
    dayCount++;
  }

  // Weekly averages
  if (dayCount > 0) {
    if (y > 700) {
      doc.addPage();
      y = margin;
    }

    y += 4;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('WEEKLY AVERAGES', margin, y);
    y += 16;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const avgCal = Math.round(totalCal / dayCount);
    const avgP = Math.round(totalProtein / dayCount);
    const avgC = Math.round(totalCarbs / dayCount);
    const avgF = Math.round(totalFat / dayCount);
    doc.text(`Avg daily:  ${avgCal} cal  |  ${avgP}g protein  |  ${avgC}g carbs  |  ${avgF}g fat`, margin + 8, y);
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 30;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Fitness Recomp App', margin, footerY);
  doc.text(new Date().toLocaleDateString(), margin + contentWidth - doc.getTextWidth(new Date().toLocaleDateString()), footerY);

  doc.save(`meal-schedule-${weekStart}.pdf`);
}
