import jsPDF from 'jspdf';

interface RecipeIngredientData {
  quantity: number;
  unit: string;
  ingredient?: { name: string };
  notes?: string | null;
}

interface RecipeData {
  name: string;
  meal_slot: string;
  prep_time_min?: number | null;
  freezer_friendly: boolean;
  batch_yield: number;
  calories_per_serving?: number | null;
  protein_per_serving?: number | null;
  carbs_per_serving?: number | null;
  fat_per_serving?: number | null;
  notes?: string | null;
  instructions?: string | null;
  ingredients?: RecipeIngredientData[];
}

export function generateRecipePDF(recipe: RecipeData) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(recipe.name.toUpperCase(), margin, y);
  y += 20;

  // Subtitle line: meal slot | prep time | freezer badge
  const badges: string[] = [
    recipe.meal_slot.charAt(0).toUpperCase() + recipe.meal_slot.slice(1),
  ];
  if (recipe.prep_time_min) badges.push(`${recipe.prep_time_min} min prep`);
  if (recipe.freezer_friendly) badges.push('Freezer-friendly');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(badges.join('  |  '), margin, y);
  y += 8;

  doc.setDrawColor(180);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentWidth, y);
  y += 20;

  doc.setTextColor(0);

  // Macros
  const cal = recipe.calories_per_serving ?? 0;
  const protein = recipe.protein_per_serving ?? 0;
  const carbs = recipe.carbs_per_serving ?? 0;
  const fat = recipe.fat_per_serving ?? 0;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('MACROS (per serving)', margin, y);
  y += 16;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${cal} cal  |  ${protein}g protein  |  ${carbs}g carbs  |  ${fat}g fat`, margin + 8, y);
  y += 24;

  // Ingredients
  if (recipe.ingredients && recipe.ingredients.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('INGREDIENTS', margin, y);
    y += 16;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    for (const ing of recipe.ingredients) {
      if (y > 720) {
        doc.addPage();
        y = margin;
      }

      const qty = ing.quantity % 1 === 0
        ? String(ing.quantity)
        : ing.quantity.toFixed(2).replace(/0+$/, '').replace(/\.$/, '');
      const name = ing.ingredient?.name || 'Unknown';
      const noteStr = ing.notes ? ` (${ing.notes})` : '';

      doc.text(`\u2022  ${qty} ${ing.unit} ${name}${noteStr}`, margin + 8, y);
      y += 14;
    }

    y += 10;
  }

  // Instructions
  if (recipe.instructions) {
    if (y > 640) {
      doc.addPage();
      y = margin;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('INSTRUCTIONS', margin, y);
    y += 16;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    const lines = recipe.instructions.split('\n');
    for (const line of lines) {
      if (y > 720) {
        doc.addPage();
        y = margin;
      }

      const trimmed = line.trim();
      if (!trimmed) {
        y += 8;
        continue;
      }

      // Check if it's a section header (all caps or starts with a keyword)
      if (trimmed === trimmed.toUpperCase() && trimmed.length > 3 && !trimmed.match(/^\d/)) {
        y += 4;
        doc.setFont('helvetica', 'bold');
        doc.text(trimmed, margin + 8, y);
        doc.setFont('helvetica', 'normal');
      } else {
        // Wrap long lines
        const splitLines = doc.splitTextToSize(trimmed, contentWidth - 16);
        for (const sl of splitLines) {
          if (y > 720) {
            doc.addPage();
            y = margin;
          }
          doc.text(sl, margin + 8, y);
          y += 14;
        }
        continue;
      }
      y += 14;
    }

    y += 10;
  }

  // Batch cooking note
  if (recipe.freezer_friendly) {
    if (y > 680) {
      doc.addPage();
      y = margin;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('BATCH COOKING', margin, y);
    y += 16;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Batch yield: ${recipe.batch_yield} servings`, margin + 8, y);
    y += 14;

    if (recipe.notes) {
      doc.setTextColor(100);
      doc.text(recipe.notes, margin + 8, y);
      doc.setTextColor(0);
    }
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 30;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Fitness Recomp App', margin, footerY);
  doc.text(new Date().toLocaleDateString(), margin + contentWidth - doc.getTextWidth(new Date().toLocaleDateString()), footerY);

  // Filename: slugify recipe name
  const slug = recipe.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  doc.save(`recipe-${slug}.pdf`);
}
